<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @package    Mage_Debit
 * @copyright  2011 ITABS GmbH / Rouven Alexander Rieker (http://www.itabs.de)
 * @copyright  2010 Phoenix Medien GmbH & Co. KG (http://www.phoenix-medien.de)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php if($_info = $this->getMethod()): ?>
<?php echo $this->htmlEscape($_info->getTitle()) ?>
    {{pdf_row_separator}}
<?php echo $this->__('Account holder: %s', $_info->getAccountName()) ?>
    {{pdf_row_separator}}
<?php echo $this->__('Account number: %s', $_info->getAccountNumber()) ?>
    {{pdf_row_separator}}
<?php echo $this->__('Bank code: %s', $_info->getAccountBLZ()) ?>
    {{pdf_row_separator}}
<?php endif; ?>