<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @package    Mage_Debit
 * @copyright  2011 ITABS GmbH / Rouven Alexander Rieker (http://www.itabs.de)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<ul id="payment_form_<?php echo $this->getMethodCode() ?>" style="display:none">
    <li>
        <div class="input-box">
            <?php if ($this->getMethod()->getCustomText()): ?>
                <?php echo $this->getMethod()->getCustomText() ?><br />
            <?php endif; ?>
        </div>
    </li>
    <li>
        <div class="input-box">
            <label for="bankleitzahl"><?php echo $this->__('Bankleitzahl') ?> <span class="required">*</span></label><br />
            <input type="text" id="bankleitzahl" name="payment[cc_type]" title="<?php echo $this->__('Bankleitzahl') ?>" class="input-text required-entry validate-number validate-debit-blz" value="<?php echo $this->getAccountBLZ() ?>" />
        </div>
    </li>
	<li>
        <div class="input-box">
            <label for="kontoinhaber"><?php echo $this->__('Kontoinhaber') ?> <span class="required">*</span></label><br />
            <input type="text" id="kontoinhaber" name="payment[cc_owner]" title="<?php echo $this->__('Kontoinhaber') ?>" class="input-text required-entry" value="<?php echo $this->getAccountName() ?>" />
        </div>
	</li>
	<li>
        <div class="input-box">
            <label for="kontonummer"><?php echo $this->__('Konto-Nummer') ?> <span class="required">*</span></label><br />
            <input type="text" id="kontonummer" name="payment[cc_number]" title="<?php echo $this->__('Konto-Nummer') ?>" class="input-text required-entry validate-number" value="<?php echo $this->getAccountNumber() ?>" />
        </div>
	</li>
</ul>
