<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @package    Mage_Debit
 * @copyright  2011 ITABS GmbH / Rouven Alexander Rieker (http://www.itabs.de)
 * @copyright  2010 Phoenix Medien GmbH & Co. KG (http://www.phoenix-medien.de)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php if ($_info = $this->getMethod()): ?>
    <?php echo $this->htmlEscape($_info->getTitle()) ?><br /><br />

	<?php if ($this->isEmailContext()): ?>
		
	    <?php // TO DO !!! ?>
        
		<?php if ($this->sendDataInEmail()): ?>
            <?php $_data = $this->getEmailData() ?>
            <?php if (!empty($_data['bank_name'])): ?>
                <?php echo $this->__('Bank name: %s', $this->htmlEscape($_data['bank_name'])) ?><br />
            <?php endif; ?>
        
            <?php echo $this->__('Bank code: %s', $this->htmlEscape($_data['account_blz'])) ?><br />
            <?php echo $this->__('Account holder: %s', $this->htmlEscape($_data['account_name'])) ?><br />
            <?php echo $this->__('Account number: %s', $this->htmlEscape($_data['account_number'])) ?><br />
        <?php endif; ?>
        
    <?php else: ?>
    
        <?php if ($_info->getAccountBankname() == Mage::helper('debit')->__('not available')): ?>
        	<span style="color: #cc0000;font-weight:bold;"><?php echo $this->__('Fehler! Die eingegebenen Bankdaten können fehlerhaft sein!<br />Bitte setzen Sie sich mit dem Kunden in Verbindung!') ?></span><br /><br />
        <?php else: ?>
            <?php echo $this->__('Bank name: %s', $this->htmlEscape($_info->getAccountBankname())) ?><br />
        <?php endif; ?>
    
        <?php echo $this->__('Bank code: %s', $this->htmlEscape($_info->getAccountBLZ())) ?><br />
        <?php echo $this->__('Account holder: %s', $this->htmlEscape($_info->getAccountName())) ?><br />
        <?php echo $this->__('Account number: %s', $this->htmlEscape($_info->getAccountNumber())) ?><br />
    
    <?php endif; ?>
    
    <br />
<?php endif; ?>