<?php
/**
 * This file is part of the Mage_Debit module.
 * 
 * NOTICE OF LICENSE
 * 
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category  Mage
 * @package   Mage_Debit
 * @author    Rouven Alexander Rieker <rouven.rieker@itabs.de>
 * @copyright 2012 ITABS GmbH / Rouven Alexander Rieker (http://www.itabs.de)
 * @copyright 2010 Phoenix Medien GmbH & Co. KG (http://www.phoenix-medien.de)
 * @license   http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * @link      http://www.magentocommerce.com/extension/676/
 */
?>
<?php if ($_info = $this->getMethod()): ?>
    <?php echo $this->htmlEscape($_info->getTitle()) ?><br />

    <?php if ($this->isEmailContext()): ?>
        <?php if ($this->sendDataInEmail()): ?>
            <?php $_data = $this->getEmailData() ?>
            <?php if (!empty($_data['bank_name'])): ?>
                <?php echo $this->__('Bank name: %s', $this->htmlEscape($_data['bank_name'])) ?><br />
            <?php endif; ?>
            
            <?php echo $this->__('Bank code: %s', $this->htmlEscape($_data['account_blz'])) ?><br />
            <?php echo $this->__('Account holder: %s', $this->htmlEscape($_data['account_name'])) ?><br />
            <?php echo $this->__('Account number: %s', $this->htmlEscape($_data['account_number'])) ?><br />
        <?php endif; ?>
        
    <?php else: ?>
        <?php echo $this->__('Bank name: %s', $this->htmlEscape($_info->getAccountBankname())) ?><br />
        <?php echo $this->__('Bank code: %s', $this->htmlEscape($_info->getAccountBLZ())) ?><br />
        <?php echo $this->__('Account holder: %s', $this->htmlEscape($_info->getAccountName())) ?><br />
        <?php echo $this->__('Account number: %s', $this->htmlEscape($_info->getAccountNumber())) ?><br />
    <?php endif; ?>

    <?php if ($_customText = $_info->getCustomText()): ?>
        <br />
        <?php echo $this->htmlEscape($_customText) ?><br />
    <?php endif; ?>
<?php endif; ?>