<?php
/**
 * This file is part of the Itabs_Debit module.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category  Itabs
 * @package   Itabs_Debit
 * @author    ITABS GmbH <info@itabs.de>
 * @copyright 2008-2014 ITABS GmbH (http://www.itabs.de)
 * @license   http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 * @version   1.1.3
 * @link      http://www.magentocommerce.com/magento-connect/debitpayment.html
 */
?>
<?php
/**
 * @var $this Itabs_Debit_Block_Form
 */
?>
<script type="text/javascript">
    //<![CDATA[
    blzCheck = new blzAjaxCheck('<?php echo $this->getUrl('debit/ajax/checkblz');?>', '0');
    //]]>
</script>
<fieldset class="form-list">
    <ul id="payment_form_<?php echo $this->getMethodCode() ?>" style="display:none">
        <?php if ($cin = $this->getCreditorIdentificationNumber()): ?>
            <p class="debit-cin"><?php echo $this->__('Our Creditor Identification Number: %s', $cin); ?></p>
        <?php endif; ?>
        <?php if ($this->getMethod()->getCustomText()): ?>
            <li>
                <div class="input-box">
                    <?php echo $this->getMethod()->getCustomText() ?><br/>
                </div>
            </li>
        <?php endif; ?>
        <li>
            <label for="kontoinhaber" class="required"><em>*</em><?php echo $this->__('Kontoinhaber') ?></label><br/>

            <div class="input-box">
                <input type="text" id="kontoinhaber" name="payment[debit_cc_owner]" title="<?php echo $this->__('Kontoinhaber') ?>" class="input-text required-entry" value="<?php echo $this->getAccountName() ?>"/>
            </div>
        </li>
        <li class="fields">
            <div class="field">
                <label for="iban" class="required"><em>*</em><?php echo $this->__('IBAN') ?></label><br/>

                <div class="input-box">
                    <input type="text" id="iban" name="payment[debit_iban]" title="<?php echo $this->__('IBAN') ?>" class="input-text required-entry validate-debit-iban" value="<?php echo $this->getAccountIban() ?>"/>
                    <?php if ($hint = $this->getHintForIbanField()): ?>
                        <p class="debit-hint"><?php echo $hint ?></p>
                    <?php endif; ?>
                </div>
            </div>
            <div class="field">
                <label for="swiftcode" class="required"><em>*</em><?php echo $this->__('SWIFT Code') ?></label><br/>

                <div class="input-box">
                    <input type="text" id="swiftcode" name="payment[debit_swift]" title="<?php echo $this->__('SWIFT Code') ?>" class="input-text required-entry validate-debit-swift" value="<?php echo $this->getAccountSwift() ?>" onblur="blzCheck.checkBlz(this); return false;"/>
                    <?php if ($hint = $this->getHintForBicField()): ?>
                        <p class="debit-hint"><?php echo $hint ?></p>
                    <?php endif; ?>
                </div>
            </div>
        </li>
        <li>
            <label for="bank_name" class="required"><em>*</em><?php echo $this->__('Bank name') ?></label>

            <div class="input-box">
                <input type="text" id="bank_name" name="payment[debit_bankname]" value="<?php echo $this->getBankName() ?>" class="input-text required-entry">
            </div>
        </li>
    </ul>
</fieldset>
