<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @package    Mage_Debit
 * @copyright  Copyright (c) 2010 Phoenix Medien GmbH & Co. KG (http://www.phoenix-medien.de)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<div class="page-title">
    <h1><?php echo $this->__('Edit Debit Account Data') ?></h1>
</div>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<form action="<?php echo $this->getUrl('debit/account/save') ?>" method="post" id="form-validate">
    <div class="fieldset">
    <?php echo $this->getBlockHtml('formkey')?>
        <h2 class="legend"><?php echo $this->__('Debit Account Data') ?></h2>
        <ul class="form-list">
            <li>
                <div class="input-box">
                    <label for="kreditinstitut"><?php echo $this->__('Kreditinstitut') ?></label><br />
                    <span id="blz_bank_name" style="display: block; padding : 0 0 0 10px; float:left;"><?php echo $this->getBankName(); ?></span>
                </div>
            </li>
            <li>
                <div class="input-box">
                    <label for="bankleitzahl"><?php echo $this->__('Bankleitzahl') ?></label><br />
                    <input type="text" id="bankleitzahl" name="account_blz" title="<?php echo $this->__('Bankleitzahl') ?>" class="input-text required-entry validate-number validate-debit-blz" value="<?php echo $this->getAccountBLZ() ?>" onchange="blzCheck.checkBlz(this); return false;" />
                </div>
            </li>
            <li>
                <div class="input-box">
                    <label for="kontoinhaber"><?php echo $this->__('Kontoinhaber') ?></label><br />
                    <input type="text" id="kontoinhaber" name="account_name" title="<?php echo $this->__('Kontoinhaber') ?>" class="input-text required-entry" value="<?php echo $this->getAccountName() ?>" />
                </div>
            </li>
            <li>
                <div class="input-box">
                    <label for="kontonummer"><?php echo $this->__('Konto-Nummer') ?></label><br />
                    <input type="text" id="kontonummer" name="account_number" title="<?php echo $this->__('Konto-Nummer') ?>" class="input-text required-entry validate-number validate-debit-number" value="<?php echo $this->getAccountNumber() ?>" />
                </div>
            </li>
        </ul>
    </div>
    <div class="buttons-set">
        <p class="required"><?php echo $this->__('* Required Fields') ?></p>
        <p class="back-link"><a href="<?php echo $this->getBackUrl() ?>"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
        <button type="submit" title="<?php echo $this->__('Save') ?>" class="button"><span><span><?php echo $this->__('Save') ?></span></span></button>
    </div>
</form>

<script type="text/javascript">
//<![CDATA[
    blzCheck = new blzAjaxCheck('<?php echo $this->getUrl('debit/ajax/checkblz');?>','1');
    var dataForm = new VarienForm('form-validate', true);
//]]>
</script>
