<?php
/**
 * This file is part of the Itabs_Debit module.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category  Itabs
 * @package   Itabs_Debit
 * @author    Rouven Alexander Rieker <rouven.rieker@itabs.de>
 * @copyright 2008-2013 ITABS GmbH / Rouven Alexander Rieker (http://www.itabs.de)
 * @license   http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * @version   1.0.2
 * @link      http://www.magentocommerce.com/magento-connect/debitpayment.html
 */
?>
<?php if($_info = $this->getMethod()): ?>
<?php echo $this->htmlEscape($_info->getTitle()) ?>
    {{pdf_row_separator}}
<?php echo $this->__('Account holder: %s', $_info->getAccountName()) ?>
    {{pdf_row_separator}}
<?php echo $this->__('Account number: %s', $_info->getAccountNumber()) ?>
    {{pdf_row_separator}}
<?php echo $this->__('Bank code: %s', $_info->getAccountBLZ()) ?>
    {{pdf_row_separator}}
<?php endif; ?>
