<?php
/**
 * This file is part of the Itabs_Debit module.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category  Itabs
 * @package   Itabs_Debit
 * @author    ITABS GmbH <info@itabs.de>
 * @copyright 2008-2014 ITABS GmbH (http://www.itabs.de)
 * @license   http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 * @version   1.1.3
 * @link      http://www.magentocommerce.com/magento-connect/debitpayment.html
 */
?>
<?php
/**
 * @var $this Itabs_Debit_Block_Form
 */
?>
<script type="text/javascript">
    //<![CDATA[
    blzCheck = new blzAjaxCheck('<?php echo $this->getUrl('debit/ajax/checkblz');?>', '<?php echo $this->getCheckoutValidBlz() ?>');
    //]]>
</script>
<fieldset class="form-list">
    <ul id="payment_form_<?php echo $this->getMethodCode() ?>" style="display:none">
        <?php if ($this->getMethod()->getCustomText()): ?>
            <li>
                <div class="input-box">
                    <?php echo $this->getMethod()->getCustomText() ?><br/>
                </div>
            </li>
        <?php endif; ?>
        <li class="fields">
            <div class="field">
                <label for="kontoinhaber" class="required"><em>*</em><?php echo $this->__('Kontoinhaber') ?></label><br/>

                <div class="input-box">
                    <input type="text" id="kontoinhaber" name="payment[debit_cc_owner]" title="<?php echo $this->__('Kontoinhaber') ?>" class="input-text required-entry" value="<?php echo $this->getAccountName() ?>"/>
                </div>
            </div>
            <div class="field">
                <label for="kontonummer" class="required"><em>*</em><?php echo $this->__('Konto-Nummer') ?></label><br/>

                <div class="input-box">
                    <input type="text" id="kontonummer" name="payment[debit_cc_number]" title="<?php echo $this->__('Konto-Nummer') ?>" maxlength="11" class="input-text required-entry validate-number validate-debit-number" value="<?php echo $this->getAccountNumber() ?>"/>
                </div>
            </div>
        </li>
        <li class="fields">
            <div class="field">
                <label for="bankleitzahl" class="required"><em>*</em><?php echo $this->__('Bankleitzahl') ?></label><br/>

                <div class="input-box">
                    <input type="text" id="bankleitzahl" name="payment[debit_cc_type]" title="<?php echo $this->__('Bankleitzahl') ?>" class="input-text required-entry validate-number validate-debit-blz" style="display: block; float: left;" value="<?php echo $this->getAccountBLZ() ?>"
                           onchange="blzCheck.checkBlz(this); return false;"/>
                </div>
            </div>
            <div class="field">
                <label for="bank_name" class="required"><em>*</em><?php echo $this->__('Bank name') ?></label>

                <div class="input-box">
                    <input type="text" id="bank_name" name="payment[debit_bankname]" value="<?php echo $this->getBankName() ?>" class="input-text required-entry">
                </div>
            </div>
        </li>
    </ul>
</fieldset>
