<?php
/**
 * This file is part of the Itabs_Debit module.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category  Itabs
 * @package   Itabs_Debit
 * @author    Rouven Alexander Rieker <rouven.rieker@itabs.de>
 * @copyright 2008-2013 ITABS GmbH / Rouven Alexander Rieker (http://www.itabs.de)
 * @license   http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * @version   1.0.2
 * @link      http://www.magentocommerce.com/magento-connect/debitpayment.html
 */
?>
<script type="text/javascript">
//<![CDATA[
blzCheck = new blzAjaxCheck('<?php echo $this->getUrl('debit/ajax/checkblz');?>','<?php echo $this->getCheckoutValidBlz() ?>');
//]]>
</script>

<fieldset class="form-list">
    <ul id="payment_form_<?php echo $this->getMethodCode() ?>" style="display:none">
        <li>
            <div class="input-box">
                <?php if ($this->getMethod()->getCustomText()): ?>
                    <?php echo $this->getMethod()->getCustomText() ?><br />
                <?php endif; ?>
            </div>
        </li>
        <li>
            <div class="input-box">
                <label for="kreditinstitut"><?php echo $this->__('Kreditinstitut') ?></label><br />
                <span id="kreditinstitut"><?php echo $this->getBankName(); ?></span>
            </div>
        </li>
        <li>
            <div class="input-box">
                <label for="bankleitzahl"><?php echo $this->__('Bankleitzahl') ?> <span class="required">*</span></label><br />
                <input type="text" id="bankleitzahl" name="payment[debit_cc_type]" title="<?php echo $this->__('Bankleitzahl') ?>" class="input-text required-entry validate-number validate-debit-blz" style="display: block; float: left;" value="<?php echo $this->getAccountBLZ() ?>" onchange="blzCheck.checkBlz(this); return false;"/>
            </div>
        </li>
        <li>
            <div class="input-box">
                <label for="kontoinhaber"><?php echo $this->__('Kontoinhaber') ?> <span class="required">*</span></label><br />
                <input type="text" id="kontoinhaber" name="payment[debit_cc_owner]" title="<?php echo $this->__('Kontoinhaber') ?>" class="input-text required-entry" value="<?php echo $this->getAccountName() ?>" />
            </div>
        </li>
        <li>
            <div class="input-box">
                <label for="kontonummer"><?php echo $this->__('Konto-Nummer') ?> <span class="required">*</span></label><br />
                <input type="text" id="kontonummer" name="payment[debit_cc_number]" title="<?php echo $this->__('Konto-Nummer') ?>" maxlength="11" class="input-text required-entry validate-number validate-debit-number" value="<?php echo $this->getAccountNumber() ?>" />
            </div>
        </li>
    </ul>
</fieldset>
