<?php
/**
 * This file is part of the Itabs_Debit module.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category  Itabs
 * @package   Itabs_Debit
 * @author    Rouven Alexander Rieker <rouven.rieker@itabs.de>
 * @copyright 2008-2014 ITABS GmbH (http://www.itabs.de)
 * @license   http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * @version   1.0.7
 * @link      http://www.magentocommerce.com/magento-connect/debitpayment.html
 */
?>
<?php
/**
 * @see Itabs_Debit_Block_Form
 * @var $this Itabs_Debit_Block_Form
 */
?>
<fieldset class="form-list">
    <ul id="payment_form_<?php echo $this->getMethodCode() ?>" style="display:none">
        <?php if ($this->getMethod()->getCustomText()): ?>
        <li><div class="input-box"><?php echo $this->getMethod()->getCustomText() ?><br /></div></li>
        <?php endif; ?>

        <li class="fields">
            <div class="field"><strong><?php echo $this->__('Bank Details')?></strong></div>
        </li>
        <li class="fields">
            <div class="field">
                <label for="iban"><?php echo $this->__('IBAN') ?> <span class="required">*</span></label><br />
                <div class="input-box">
                    <input type="text" id="iban" name="payment[debit_iban]" title="<?php echo $this->__('IBAN') ?>" class="input-text required-entry" value="<?php echo $this->getAccountIban() ?>" />
                    <?php if ($hint = $this->getHintForIbanField()): ?>
                        <p class="debit-hint"><?php echo $hint?></p>
                    <?php endif; ?>
                </div>
            </div>
            <div class="field">
                <label for="swiftcode"><?php echo $this->__('SWIFT Code') ?> <span class="required">*</span></label><br />
                <div class="input-box">
                    <input type="text" id="swiftcode" name="payment[debit_swift]" title="<?php echo $this->__('SWIFT Code') ?>" class="input-text required-entry" value="<?php echo $this->getAccountSwift() ?>" />
                    <?php if ($hint = $this->getHintForSwiftField()): ?>
                        <p class="debit-hint"><?php echo $hint?></p>
                    <?php endif; ?>
                </div>
            </div>
        </li>

        <li class="fields">
            <div class="field"><strong><?php echo $this->__('Account Holder')?></strong></div>
        </li>
        <li class="fields">
            <div class="field">
                <label for="kontoinhaber"><?php echo $this->__('Name') ?> <span class="required">*</span></label><br />
                <div class="input-box">
                    <input type="text" id="kontoinhaber" name="payment[debit_cc_owner]" title="<?php echo $this->__('Name') ?>" class="input-text required-entry" value="<?php echo $this->getAccountName() ?>" />
                </div>
            </div>
        </li>

        <?php if ($this->helper('debit')->isGenerateMandate()): ?>
        <li class="fields">
            <div class="field">
                <label for="debit_company"><?php echo $this->helper('customer')->__('Company') ?></label><br />
                <div class="input-box">
                    <input type="text" id="debit_company" name="payment[debit_company]" title="<?php echo $this->__('Company') ?>" class="input-text" value="<?php echo $this->getAccountCompany() ?>" />
                </div>
            </div>
        </li>
        <li class="fields">
            <div class="field">
                <label for="debit_street"><?php echo $this->__('Street and Housenumber') ?> <span class="required">*</span></label><br />
                <div class="input-box">
                    <input type="text" id="debit_street" name="payment[debit_street]" title="<?php echo $this->__('Street') ?>" class="input-text required-entry" value="<?php echo $this->getAccountStreet() ?>" />
                </div>
            </div>
            <div class="field">
                <label for="debit_city"><?php echo $this->__('Postcode/City') ?> <span class="required">*</span></label><br />
                <div class="input-box">
                    <input type="text" id="debit_city" name="payment[debit_city]" title="<?php echo $this->__('Postcode/City') ?>" class="input-text required-entry" value="<?php echo $this->getAccountCity() ?>" />
                </div>
            </div>
        </li>
        <li class="fields">
            <div class="field">
                <label for="debit_country"><?php echo $this->helper('customer')->__('Country') ?> <span class="required">*</span></label><br />
                <div class="input-box">
                    <?php echo $this->getCountryHtmlSelect()?>
                </div>
            </div>
            <div class="field">
                <label for="debit_email"><?php echo $this->helper('customer')->__('Email Address') ?> <span class="required">*</span></label><br />
                <div class="input-box">
                    <input type="text" id="debit_email" name="payment[debit_email]" title="<?php echo $this->__('Email') ?>" class="input-text required-entry validate-email" value="<?php echo $this->getAccountEmail() ?>" />
                </div>
            </div>
        </li>
        <?php endif; ?>
    </ul>
</fieldset>
