<?php
/**
 * This file is part of the Itabs_Debit module.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category  Itabs
 * @package   Itabs_Debit
 * @author    ITABS GmbH <info@itabs.de>
 * @copyright 2008-2014 ITABS GmbH (http://www.itabs.de)
 * @license   http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 * @version   1.1.3
 * @link      http://www.magentocommerce.com/magento-connect/debitpayment.html
 */
?>
<?php
/**
 * @var $this Itabs_Debit_Block_Account_Data
 */
?>
<div class="page-title">
    <h1><?php echo $this->__('Edit Debit Account Data') ?></h1>
</div>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<form action="<?php echo $this->getUrl('debit/account/save') ?>" method="post" id="form-validate">
    <div class="fieldset">
        <?php echo $this->getBlockHtml('formkey')?>
        <h2 class="legend"><?php echo $this->__('Debit Account Data') ?></h2>
        <?php if ($cin = $this->getCreditorIdentificationNumber()): ?>
        <p class="debit-cin"><?php echo $this->__('Our Creditor Identification Number: %s', $cin); ?></p>
        <?php endif; ?>
        <ul class="form-list">
            <li>
                <label for="kontoinhaber" class="required"><em>*</em><?php echo $this->__('Kontoinhaber') ?></label><br />
                <div class="input-box">
                    <input type="text" id="kontoinhaber" name="account_name" title="<?php echo $this->__('Kontoinhaber') ?>" class="input-text required-entry" value="<?php echo $this->getAccountName() ?>" />
                </div>
            </li>
            <li class="fields">
                <div class="field">
                    <label for="iban" class="required"><em>*</em><?php echo $this->__('IBAN') ?></label><br />
                    <div class="input-box">
                        <input type="text" id="iban" name="account_iban" title="<?php echo $this->__('IBAN') ?>" class="input-text required-entry validate-debit-iban" value="<?php echo $this->getAccountIban() ?>" />
                        <?php if ($hint = $this->getHintForIbanField()): ?>
                            <p class="debit-hint"><?php echo $hint?></p>
                        <?php endif; ?>
                    </div>
                </div>
                <div class="field">
                    <label for="swiftcode" class="required"><em>*</em><?php echo $this->__('SWIFT Code') ?></label><br />
                    <div class="input-box">
                        <input type="text" id="swiftcode" name="account_swift" title="<?php echo $this->__('SWIFT Code') ?>" class="input-text required-entry validate-debit-swift" onblur="blzCheck.checkBlz(this);" value="<?php echo $this->getAccountSwift() ?>" />
                        <?php if ($hint = $this->getHintForBicField()): ?>
                            <p class="debit-hint"><?php echo $hint?></p>
                        <?php endif; ?>
                    </div>
                </div>
            </li>
            <li>
                <label for="bank_name" class="required"><em>*</em><?php echo $this->__('Bank name') ?></label>
                <div class="input-box">
                    <input type="text" id="bank_name" name="bank_name" value="<?php echo $this->getBankName()?>" class="input-text required-entry">
                </div>
            </li>
        </ul>
    </div>
    <div class="buttons-set">
        <p class="required"><?php echo $this->__('* Required Fields') ?></p>
        <p class="back-link"><a href="<?php echo $this->getBackUrl() ?>"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
        <button type="submit" title="<?php echo $this->__('Save') ?>" class="button"><span><span><?php echo $this->__('Save') ?></span></span></button>
    </div>
</form>

<script type="text/javascript">
//<![CDATA[
    blzCheck = new blzAjaxCheck('<?php echo $this->getUrl('debit/ajax/checkblz');?>', '0');
    var dataForm = new VarienForm('form-validate', true);
//]]>
</script>

